### ISSUE TITLE
example to implement in iOS

### ISSUE THREAD

**Issue by Nathan187** [naturalistic/RaiseKeyboard#3]
this appears to be useful but it doesn't show really how to do this in a dedicated ios project.  not using xamarin forms.  can this still be done?

**Comment by naturalistic** [comment]
Hi Nathan - you can make use of the code in the iOS service which detects the keyboard has raised. Instead of creating a service you can use the code in your iOS project directly and adjust the height of your scroll-view. 

https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

**Comment by Nathan187** [comment]
i can't do that for _IKeyboardHelper_ is not defined anywhere in the iOS project.

**Comment by Nathan187** [comment]
i think i was able to figure it out and it _seems_ to work.  however, it's only working on textfields.  doesn't work for textviews.   thank you however!

**Comment by naturalistic** [comment]
Check out the code in 'KeyboardHelper.cs' in the iOS project. If you subscribe to the keyboard raise and lower events you should be able to detect the keyboard appearing and hiding. The code in the function 'OnKeyboardNotification' shows you how to calculate the height of the keyboard, so you can adjust your view by that much.
